/*
 * sys/codegen/lib/petscOptionsDestroy/petscOptionsDestroy_mex.c
 *
 * Auxiliary code for mexFunction of petscOptionsDestroy
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {PetscOptions}  enableInline=1 withPetsc=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "petscOptionsDestroy.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void petscOptionsDestroy_api(const mxArray ** prhs, const mxArray **plhs) {

    struct0_T            opts;
    mxArray              *_sub_mx1;

    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */
    plhs[0] = mxDuplicateArray(prhs[0]);

    if (!mxIsStruct(plhs[0]))
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongInputType",
            "Input argument opts has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(plhs[0])!=3)
        mexErrMsgIdAndTxt("petscOptionsDestroy:InputStructWrongFields",
            "Input argument opts has incorrect number of fields.");
    if (mxGetNumberOfElements(plhs[0]) != 1)
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongSizeOfInputArg",
            "Argument opts must contain 1 items.");

    _sub_mx1 = mxGetField(plhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongInputStruct",
            "Input argument opts does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongInputType",
            "Input argument opts.data has incorrect data type. uint8 is expected.");
    *(void**)&opts.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)opts.data, "opts.data", 1);
    _sub_mx1 = mxGetField(plhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongInputStruct",
            "Input argument opts does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongInputType",
            "Input argument opts.type has incorrect data type. char is expected.");
    *(void**)&opts.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)opts.type, "opts.type", 2);
    _sub_mx1 = mxGetField(plhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongInputStruct",
            "Input argument opts does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongInputType",
            "Input argument opts.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongSizeOfInputArg",
            "Argument opts.nitems should be a scalar.");
    opts.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscOptionsDestroy_initialize();

    petscOptionsDestroy(&opts, errCode, toplevel);

    petscOptionsDestroy_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "data", "type", "nitems",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 3, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, move_emxArray_to_mxArray((emxArray__common*)opts.data, mxUINT8_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, move_emxArray_to_mxArray((emxArray__common*)opts.type, mxCHAR_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_scalar_to_mxArray(&opts.nitems, mxINT32_CLASS));
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)opts.type); mxFree(opts.type);
    free_emxArray((emxArray__common*)opts.data); mxFree(opts.data);

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 1) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("petscOptionsDestroy:TooManyOutputArguments","Too many output arguments for entry-point petscOptionsDestroy.");
        /* Call the API function. */
        petscOptionsDestroy_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("petscOptionsDestroy:WrongNumberOfInputs","Incorrect number of input variables for entry-point petscOptionsDestroy.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}