/*
 * codegen/lib/mptKSPSolve/mptKSPSolve_mex.c
 *
 * Auxiliary code for mexFunction of mptKSPSolve
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {PetscKSP, PetscVec, PetscVec, 0, int32(0), PetscVec} mptKSPSolve_2args -args {PetscKSP, PetscVec} mptKSPSolve_3args -args {PetscKSP, PetscVec, PetscVec} mptKSPSolve_4args -args {PetscKSP, PetscVec, PetscVec, 0} mptKSPSolve_5args -args {PetscKSP, PetscVec, PetscVec, 0, int32(0)}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "mptKSPSolve.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void mptKSPSolve_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      reshis;

    struct0_T            ksp;
    struct0_T            b;
    struct0_T            x;
    struct0_T            x0;
    mxArray              *_sub_mx1;

    real64_T             rtol;
    int32_T              maxits;
    int32_T              *flag;
    real64_T             *   relres;
    int32_T              *iter;
    real64_T             *time;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument ksp has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve:InputStructWrongFields",
            "Input argument ksp has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument ksp must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument ksp does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument ksp.data has incorrect data type. uint8 is expected.");
    *(void**)&ksp.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.data, "ksp.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument ksp does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument ksp.type has incorrect data type. char is expected.");
    *(void**)&ksp.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.type, "ksp.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument ksp does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument ksp.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument ksp.nitems should be a scalar.");
    ksp.nitems = *(int32_T*)mxGetData(_sub_mx1);

    if (!mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument b has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[1])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve:InputStructWrongFields",
            "Input argument b has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument b must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[1], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument b does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument b.data has incorrect data type. uint8 is expected.");
    *(void**)&b.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.data, "b.data", 1);
    _sub_mx1 = mxGetField(prhs[1], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument b does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument b.type has incorrect data type. char is expected.");
    *(void**)&b.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.type, "b.type", 2);
    _sub_mx1 = mxGetField(prhs[1], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument b does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument b.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument b.nitems should be a scalar.");
    b.nitems = *(int32_T*)mxGetData(_sub_mx1);

    if (!mxIsStruct(prhs[2]))
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument x has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[2])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve:InputStructWrongFields",
            "Input argument x has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument x must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[2], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument x does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument x.data has incorrect data type. uint8 is expected.");
    *(void**)&x.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x.data, "x.data", 1);
    _sub_mx1 = mxGetField(prhs[2], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument x does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument x.type has incorrect data type. char is expected.");
    *(void**)&x.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x.type, "x.type", 2);
    _sub_mx1 = mxGetField(prhs[2], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument x does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument x.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument x.nitems should be a scalar.");
    x.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument rtol has incorrect data type. double is expected.");
    if (mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument rtol should be a scalar.");
    rtol = *(real64_T*)mxGetData(prhs[3]);
    if (mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument maxits has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument maxits should be a scalar.");
    maxits = *(int32_T*)mxGetData(prhs[4]);

    if (!mxIsStruct(prhs[5]))
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument x0 has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[5])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve:InputStructWrongFields",
            "Input argument x0 has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[5]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument x0 must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[5], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument x0 does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument x0.data has incorrect data type. uint8 is expected.");
    *(void**)&x0.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x0.data, "x0.data", 1);
    _sub_mx1 = mxGetField(prhs[5], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument x0 does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument x0.type has incorrect data type. char is expected.");
    *(void**)&x0.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x0.type, "x0.type", 2);
    _sub_mx1 = mxGetField(prhs[5], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputStruct",
            "Input argument x0 does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongInputType",
            "Input argument x0.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve:WrongSizeOfInputArg",
            "Argument x0.nitems should be a scalar.");
    x0.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&flag = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&relres = prealloc_mxArray((mxArray**)&plhs[1], mxDOUBLE_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&iter = prealloc_mxArray((mxArray**)&plhs[2], mxINT32_CLASS, 2, l_size); }
    init_emxArray((emxArray__common*)&reshis, 1);
    {mwSize l_size[] = {1, 1};
    *(void **)&time = prealloc_mxArray((mxArray**)&plhs[4], mxDOUBLE_CLASS, 2, l_size); }

    /* Invoke the target function */
    mptKSPSolve_initialize();

    mptKSPSolve(&ksp, &b, &x, rtol, maxits, &x0, flag, relres, iter, &reshis, time);

    mptKSPSolve_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */
    plhs[3] = move_emxArray_to_mxArray((emxArray__common*)&reshis, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[4] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)ksp.type); mxFree(ksp.type);
    free_emxArray((emxArray__common*)ksp.data); mxFree(ksp.data);

    free_emxArray((emxArray__common*)b.type); mxFree(b.type);
    free_emxArray((emxArray__common*)b.data); mxFree(b.data);

    free_emxArray((emxArray__common*)x.type); mxFree(x.type);
    free_emxArray((emxArray__common*)x.data); mxFree(x.data);

    free_emxArray((emxArray__common*)x0.type); mxFree(x0.type);
    free_emxArray((emxArray__common*)x0.data); mxFree(x0.data);

    free_emxArray((emxArray__common*)&reshis);
}
void mptKSPSolve_2args_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      reshis;

    struct0_T            ksp;
    struct0_T            b;
    mxArray              *_sub_mx1;

    int32_T              *flag;
    real64_T             *relres;
    int32_T              *iter;
    real64_T             *time;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputType",
            "Input argument ksp has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:InputStructWrongFields",
            "Input argument ksp has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongSizeOfInputArg",
            "Argument ksp must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputStruct",
            "Input argument ksp does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputType",
            "Input argument ksp.data has incorrect data type. uint8 is expected.");
    *(void**)&ksp.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.data, "ksp.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputStruct",
            "Input argument ksp does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputType",
            "Input argument ksp.type has incorrect data type. char is expected.");
    *(void**)&ksp.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.type, "ksp.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputStruct",
            "Input argument ksp does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputType",
            "Input argument ksp.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongSizeOfInputArg",
            "Argument ksp.nitems should be a scalar.");
    ksp.nitems = *(int32_T*)mxGetData(_sub_mx1);

    if (!mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputType",
            "Input argument b has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[1])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:InputStructWrongFields",
            "Input argument b has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongSizeOfInputArg",
            "Argument b must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[1], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputStruct",
            "Input argument b does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputType",
            "Input argument b.data has incorrect data type. uint8 is expected.");
    *(void**)&b.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.data, "b.data", 1);
    _sub_mx1 = mxGetField(prhs[1], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputStruct",
            "Input argument b does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputType",
            "Input argument b.type has incorrect data type. char is expected.");
    *(void**)&b.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.type, "b.type", 2);
    _sub_mx1 = mxGetField(prhs[1], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputStruct",
            "Input argument b does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongInputType",
            "Input argument b.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_2args:WrongSizeOfInputArg",
            "Argument b.nitems should be a scalar.");
    b.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&flag = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&relres = prealloc_mxArray((mxArray**)&plhs[1], mxDOUBLE_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&iter = prealloc_mxArray((mxArray**)&plhs[2], mxINT32_CLASS, 2, l_size); }
    init_emxArray((emxArray__common*)&reshis, 1);
    {mwSize l_size[] = {1, 1};
    *(void **)&time = prealloc_mxArray((mxArray**)&plhs[4], mxDOUBLE_CLASS, 2, l_size); }

    /* Invoke the target function */
    mptKSPSolve_initialize();

    mptKSPSolve_2args(&ksp, &b, flag, relres, iter, &reshis, time);

    mptKSPSolve_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */
    plhs[3] = move_emxArray_to_mxArray((emxArray__common*)&reshis, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[4] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)ksp.type); mxFree(ksp.type);
    free_emxArray((emxArray__common*)ksp.data); mxFree(ksp.data);

    free_emxArray((emxArray__common*)b.type); mxFree(b.type);
    free_emxArray((emxArray__common*)b.data); mxFree(b.data);

    free_emxArray((emxArray__common*)&reshis);
}
void mptKSPSolve_3args_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      reshis;

    struct0_T            ksp;
    struct0_T            b;
    struct0_T            x;
    mxArray              *_sub_mx1;

    int32_T              *flag;
    real64_T             *relres;
    int32_T              *iter;
    real64_T             *time;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument ksp has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:InputStructWrongFields",
            "Input argument ksp has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongSizeOfInputArg",
            "Argument ksp must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputStruct",
            "Input argument ksp does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument ksp.data has incorrect data type. uint8 is expected.");
    *(void**)&ksp.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.data, "ksp.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputStruct",
            "Input argument ksp does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument ksp.type has incorrect data type. char is expected.");
    *(void**)&ksp.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.type, "ksp.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputStruct",
            "Input argument ksp does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument ksp.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongSizeOfInputArg",
            "Argument ksp.nitems should be a scalar.");
    ksp.nitems = *(int32_T*)mxGetData(_sub_mx1);

    if (!mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument b has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[1])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:InputStructWrongFields",
            "Input argument b has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongSizeOfInputArg",
            "Argument b must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[1], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputStruct",
            "Input argument b does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument b.data has incorrect data type. uint8 is expected.");
    *(void**)&b.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.data, "b.data", 1);
    _sub_mx1 = mxGetField(prhs[1], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputStruct",
            "Input argument b does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument b.type has incorrect data type. char is expected.");
    *(void**)&b.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.type, "b.type", 2);
    _sub_mx1 = mxGetField(prhs[1], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputStruct",
            "Input argument b does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument b.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongSizeOfInputArg",
            "Argument b.nitems should be a scalar.");
    b.nitems = *(int32_T*)mxGetData(_sub_mx1);

    if (!mxIsStruct(prhs[2]))
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument x has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[2])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:InputStructWrongFields",
            "Input argument x has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongSizeOfInputArg",
            "Argument x must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[2], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputStruct",
            "Input argument x does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument x.data has incorrect data type. uint8 is expected.");
    *(void**)&x.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x.data, "x.data", 1);
    _sub_mx1 = mxGetField(prhs[2], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputStruct",
            "Input argument x does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument x.type has incorrect data type. char is expected.");
    *(void**)&x.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x.type, "x.type", 2);
    _sub_mx1 = mxGetField(prhs[2], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputStruct",
            "Input argument x does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongInputType",
            "Input argument x.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_3args:WrongSizeOfInputArg",
            "Argument x.nitems should be a scalar.");
    x.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&flag = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&relres = prealloc_mxArray((mxArray**)&plhs[1], mxDOUBLE_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&iter = prealloc_mxArray((mxArray**)&plhs[2], mxINT32_CLASS, 2, l_size); }
    init_emxArray((emxArray__common*)&reshis, 1);
    {mwSize l_size[] = {1, 1};
    *(void **)&time = prealloc_mxArray((mxArray**)&plhs[4], mxDOUBLE_CLASS, 2, l_size); }

    /* Invoke the target function */
    mptKSPSolve_initialize();

    mptKSPSolve_3args(&ksp, &b, &x, flag, relres, iter, &reshis, time);

    mptKSPSolve_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */
    plhs[3] = move_emxArray_to_mxArray((emxArray__common*)&reshis, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[4] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)ksp.type); mxFree(ksp.type);
    free_emxArray((emxArray__common*)ksp.data); mxFree(ksp.data);

    free_emxArray((emxArray__common*)b.type); mxFree(b.type);
    free_emxArray((emxArray__common*)b.data); mxFree(b.data);

    free_emxArray((emxArray__common*)x.type); mxFree(x.type);
    free_emxArray((emxArray__common*)x.data); mxFree(x.data);

    free_emxArray((emxArray__common*)&reshis);
}
void mptKSPSolve_4args_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      reshis;

    struct0_T            ksp;
    struct0_T            b;
    struct0_T            x;
    mxArray              *_sub_mx1;

    real64_T             rtol;
    int32_T              *flag;
    real64_T             *relres;
    int32_T              *iter;
    real64_T             *time;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument ksp has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:InputStructWrongFields",
            "Input argument ksp has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongSizeOfInputArg",
            "Argument ksp must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputStruct",
            "Input argument ksp does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument ksp.data has incorrect data type. uint8 is expected.");
    *(void**)&ksp.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.data, "ksp.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputStruct",
            "Input argument ksp does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument ksp.type has incorrect data type. char is expected.");
    *(void**)&ksp.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.type, "ksp.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputStruct",
            "Input argument ksp does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument ksp.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongSizeOfInputArg",
            "Argument ksp.nitems should be a scalar.");
    ksp.nitems = *(int32_T*)mxGetData(_sub_mx1);

    if (!mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument b has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[1])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:InputStructWrongFields",
            "Input argument b has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongSizeOfInputArg",
            "Argument b must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[1], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputStruct",
            "Input argument b does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument b.data has incorrect data type. uint8 is expected.");
    *(void**)&b.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.data, "b.data", 1);
    _sub_mx1 = mxGetField(prhs[1], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputStruct",
            "Input argument b does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument b.type has incorrect data type. char is expected.");
    *(void**)&b.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.type, "b.type", 2);
    _sub_mx1 = mxGetField(prhs[1], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputStruct",
            "Input argument b does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument b.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongSizeOfInputArg",
            "Argument b.nitems should be a scalar.");
    b.nitems = *(int32_T*)mxGetData(_sub_mx1);

    if (!mxIsStruct(prhs[2]))
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument x has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[2])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:InputStructWrongFields",
            "Input argument x has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongSizeOfInputArg",
            "Argument x must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[2], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputStruct",
            "Input argument x does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument x.data has incorrect data type. uint8 is expected.");
    *(void**)&x.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x.data, "x.data", 1);
    _sub_mx1 = mxGetField(prhs[2], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputStruct",
            "Input argument x does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument x.type has incorrect data type. char is expected.");
    *(void**)&x.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x.type, "x.type", 2);
    _sub_mx1 = mxGetField(prhs[2], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputStruct",
            "Input argument x does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument x.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongSizeOfInputArg",
            "Argument x.nitems should be a scalar.");
    x.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongInputType",
            "Input argument rtol has incorrect data type. double is expected.");
    if (mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_4args:WrongSizeOfInputArg",
            "Argument rtol should be a scalar.");
    rtol = *(real64_T*)mxGetData(prhs[3]);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&flag = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&relres = prealloc_mxArray((mxArray**)&plhs[1], mxDOUBLE_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&iter = prealloc_mxArray((mxArray**)&plhs[2], mxINT32_CLASS, 2, l_size); }
    init_emxArray((emxArray__common*)&reshis, 1);
    {mwSize l_size[] = {1, 1};
    *(void **)&time = prealloc_mxArray((mxArray**)&plhs[4], mxDOUBLE_CLASS, 2, l_size); }

    /* Invoke the target function */
    mptKSPSolve_initialize();

    mptKSPSolve_4args(&ksp, &b, &x, rtol, flag, relres, iter, &reshis, time);

    mptKSPSolve_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */
    plhs[3] = move_emxArray_to_mxArray((emxArray__common*)&reshis, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[4] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)ksp.type); mxFree(ksp.type);
    free_emxArray((emxArray__common*)ksp.data); mxFree(ksp.data);

    free_emxArray((emxArray__common*)b.type); mxFree(b.type);
    free_emxArray((emxArray__common*)b.data); mxFree(b.data);

    free_emxArray((emxArray__common*)x.type); mxFree(x.type);
    free_emxArray((emxArray__common*)x.data); mxFree(x.data);

    free_emxArray((emxArray__common*)&reshis);
}
void mptKSPSolve_5args_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      reshis;

    struct0_T            ksp;
    struct0_T            b;
    struct0_T            x;
    mxArray              *_sub_mx1;

    real64_T             rtol;
    int32_T              maxiter;
    int32_T              *flag;
    real64_T             *relres;
    int32_T              *iter;
    real64_T             *time;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument ksp has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:InputStructWrongFields",
            "Input argument ksp has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongSizeOfInputArg",
            "Argument ksp must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputStruct",
            "Input argument ksp does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument ksp.data has incorrect data type. uint8 is expected.");
    *(void**)&ksp.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.data, "ksp.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputStruct",
            "Input argument ksp does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument ksp.type has incorrect data type. char is expected.");
    *(void**)&ksp.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)ksp.type, "ksp.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputStruct",
            "Input argument ksp does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument ksp.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongSizeOfInputArg",
            "Argument ksp.nitems should be a scalar.");
    ksp.nitems = *(int32_T*)mxGetData(_sub_mx1);

    if (!mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument b has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[1])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:InputStructWrongFields",
            "Input argument b has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongSizeOfInputArg",
            "Argument b must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[1], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputStruct",
            "Input argument b does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument b.data has incorrect data type. uint8 is expected.");
    *(void**)&b.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.data, "b.data", 1);
    _sub_mx1 = mxGetField(prhs[1], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputStruct",
            "Input argument b does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument b.type has incorrect data type. char is expected.");
    *(void**)&b.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)b.type, "b.type", 2);
    _sub_mx1 = mxGetField(prhs[1], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputStruct",
            "Input argument b does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument b.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongSizeOfInputArg",
            "Argument b.nitems should be a scalar.");
    b.nitems = *(int32_T*)mxGetData(_sub_mx1);

    if (!mxIsStruct(prhs[2]))
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument x has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[2])!=3)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:InputStructWrongFields",
            "Input argument x has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongSizeOfInputArg",
            "Argument x must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[2], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputStruct",
            "Input argument x does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument x.data has incorrect data type. uint8 is expected.");
    *(void**)&x.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x.data, "x.data", 1);
    _sub_mx1 = mxGetField(prhs[2], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputStruct",
            "Input argument x does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument x.type has incorrect data type. char is expected.");
    *(void**)&x.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)x.type, "x.type", 2);
    _sub_mx1 = mxGetField(prhs[2], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputStruct",
            "Input argument x does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument x.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongSizeOfInputArg",
            "Argument x.nitems should be a scalar.");
    x.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument rtol has incorrect data type. double is expected.");
    if (mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongSizeOfInputArg",
            "Argument rtol should be a scalar.");
    rtol = *(real64_T*)mxGetData(prhs[3]);
    if (mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongInputType",
            "Input argument maxiter has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("mptKSPSolve_5args:WrongSizeOfInputArg",
            "Argument maxiter should be a scalar.");
    maxiter = *(int32_T*)mxGetData(prhs[4]);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&flag = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&relres = prealloc_mxArray((mxArray**)&plhs[1], mxDOUBLE_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&iter = prealloc_mxArray((mxArray**)&plhs[2], mxINT32_CLASS, 2, l_size); }
    init_emxArray((emxArray__common*)&reshis, 1);
    {mwSize l_size[] = {1, 1};
    *(void **)&time = prealloc_mxArray((mxArray**)&plhs[4], mxDOUBLE_CLASS, 2, l_size); }

    /* Invoke the target function */
    mptKSPSolve_initialize();

    mptKSPSolve_5args(&ksp, &b, &x, rtol, maxiter, flag, relres, iter, &reshis, time);

    mptKSPSolve_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */
    plhs[3] = move_emxArray_to_mxArray((emxArray__common*)&reshis, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[4] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)ksp.type); mxFree(ksp.type);
    free_emxArray((emxArray__common*)ksp.data); mxFree(ksp.data);

    free_emxArray((emxArray__common*)b.type); mxFree(b.type);
    free_emxArray((emxArray__common*)b.data); mxFree(b.data);

    free_emxArray((emxArray__common*)x.type); mxFree(x.type);
    free_emxArray((emxArray__common*)x.data); mxFree(x.data);

    free_emxArray((emxArray__common*)&reshis);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[5];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 6) {
        if (nlhs > 5)
            mexErrMsgIdAndTxt("mptKSPSolve:TooManyOutputArguments","Too many output arguments for entry-point mptKSPSolve.");
        /* Call the API function. */
        mptKSPSolve_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 2) {
        if (nlhs > 5)
            mexErrMsgIdAndTxt("mptKSPSolve_2args:TooManyOutputArguments","Too many output arguments for entry-point mptKSPSolve_2args.");
        /* Call the API function. */
        mptKSPSolve_2args_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 3) {
        if (nlhs > 5)
            mexErrMsgIdAndTxt("mptKSPSolve_3args:TooManyOutputArguments","Too many output arguments for entry-point mptKSPSolve_3args.");
        /* Call the API function. */
        mptKSPSolve_3args_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 4) {
        if (nlhs > 5)
            mexErrMsgIdAndTxt("mptKSPSolve_4args:TooManyOutputArguments","Too many output arguments for entry-point mptKSPSolve_4args.");
        /* Call the API function. */
        mptKSPSolve_4args_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 5) {
        if (nlhs > 5)
            mexErrMsgIdAndTxt("mptKSPSolve_5args:TooManyOutputArguments","Too many output arguments for entry-point mptKSPSolve_5args.");
        /* Call the API function. */
        mptKSPSolve_5args_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("mptKSPSolve:WrongNumberOfInputs","Incorrect number of input variables for entry-point mptKSPSolve.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}