/*
 * codegen/lib/mptMatAIJToCRS/mptMatAIJToCRS_mex.c
 *
 * Auxiliary code for mexFunction of mptMatAIJToCRS
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {PetscMat}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "mptMatAIJToCRS.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void mptMatAIJToCRS_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     row_ptr;
    emxArray_int32_T     col_ind;
    emxArray_real_T      val;

    struct0_T            mat;
    mxArray              *_sub_mx1;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongInputType",
            "Input argument mat has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("mptMatAIJToCRS:InputStructWrongFields",
            "Input argument mat has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongSizeOfInputArg",
            "Argument mat must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongInputStruct",
            "Input argument mat does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongInputType",
            "Input argument mat.data has incorrect data type. uint8 is expected.");
    *(void**)&mat.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)mat.data, "mat.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongInputStruct",
            "Input argument mat does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongInputType",
            "Input argument mat.type has incorrect data type. char is expected.");
    *(void**)&mat.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)mat.type, "mat.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongInputStruct",
            "Input argument mat does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongInputType",
            "Input argument mat.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongSizeOfInputArg",
            "Argument mat.nitems should be a scalar.");
    mat.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&row_ptr, 1);
    init_emxArray((emxArray__common*)&col_ind, 1);
    init_emxArray((emxArray__common*)&val, 1);

    /* Invoke the target function */
    mptMatAIJToCRS_initialize();

    mptMatAIJToCRS(&mat, &row_ptr, &col_ind, &val);

    mptMatAIJToCRS_terminate();

    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&row_ptr, mxINT32_CLASS);
    plhs[1] = move_emxArray_to_mxArray((emxArray__common*)&col_ind, mxINT32_CLASS);
    plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&val, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray((emxArray__common*)mat.type); mxFree(mat.type);
    free_emxArray((emxArray__common*)mat.data); mxFree(mat.data);

    free_emxArray((emxArray__common*)&row_ptr);
    free_emxArray((emxArray__common*)&col_ind);
    free_emxArray((emxArray__common*)&val);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 1) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("mptMatAIJToCRS:TooManyOutputArguments","Too many output arguments for entry-point mptMatAIJToCRS.");
        /* Call the API function. */
        mptMatAIJToCRS_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("mptMatAIJToCRS:WrongNumberOfInputs","Incorrect number of input variables for entry-point mptMatAIJToCRS.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}