function build(varargin)

opts = [{'-mex', '-O', '-g', '-petsc'} varargin{:}];
files = {...
    ... % Top-level functions
    'mptKSPSetup', 'mptKSPSolve', 'mptKSPCleanup', 'mptMatCreateAIJFromCRS', ...
    'mptMatAIJToCRS', 'mptVecCreateFromArray', 'mptVecToArray', ...
    ... % System and options
    'petscInitialize', 'petscInitialized', 'petscFinalize', 'petscFinalized', ...
    'petscOptionsCreate', 'petscOptionsSetValue', 'petscOptionsInsertString', ...
    'petscOptionsInsertFile', 'petscOptionsHasName', 'petscOptionsGetInt',  ... 
    'petscOptionsGetReal', 'petscOptionsGetString', 'petscOptionsDestroy', ...
    ... % Vector
    'petscVecCreate', 'petscVecCreateSeq', 'petscVecDuplicate', 'petscVecSetType', ...
    'petscVecSetOption', 'petscVecSetOptionsPrefix', 'petscVecSetFromOptions', ...
    'petscVecSetSizes', 'petscVecSetValues', 'petscVecSet', 'petscVecCopy', ...
    'petscVecGetSize', 'petscVecGetLocalSize', ...
    'petscVecGetValues', 'petscVecGetOwnershipRange', ...
    'petscVecAssemblyBegin', 'petscVecAssemblyEnd', 'petscVecDestroy', ...
    ... % Matrix
    'petscMatCreate', 'petscMatCreateSeqAIJ', 'petscMatSetType', ...
    'petscMatSeqAIJSetPreallocationCSR', 'petscMatMPIAIJSetPreallocationCSR', ...
    'petscMatSetOption', 'petscMatSetOptionsPrefix', 'petscMatSetFromOptions', ...
    'petscMatSetSizes', 'petscMatSetValues', 'petscMatCopy', 'petscMatConvert', ...
    'petscMatGetSize', 'petscMatGetLocalSize', 'petscMatGetInfo', ...
    'petscMatGetValues', 'petscMatGetRow', ...
    'petscMatAssemblyBegin', 'petscMatAssemblyEnd', 'petscMatAssembled', ...
    'petscMatDestroy', 'petscMatGetOwnershipRange', ...
    ... %KSP
    'petscKSPCreate', 'petscKSPSetType', 'petscKSPSetOperators', ...
    'petscKSPSetPC', 'petscKSPSetTolerances', ...
    'petscKSPSetInitialGuessNonzero', 'petscKSPGetInitialGuessNonzero', ...
    'petscKSPSetOptionsPrefix', 'petscKSPAppendOptionsPrefix', 'petscKSPSetFromOptions', ...
    'petscKSPSetUp', 'petscKSPSolve', 'petscKSPBuildResidual', ...
    'petscKSPGetType', 'petscKSPGetOptionsPrefix', ...
    'petscKSPGetPC', 'petscKSPGetIterationNumber', ...
    'petscKSPGetTotalIterations', 'petscKSPGetResidualNorm', ...
    'petscKSPDestroy', ...
    ... %PC
    'petscPCCreate', 'petscPCSetType', 'petscPCSetOperators', ...
    'petscPCSetOptionsPrefix', 'petscPCAppendOptionsPrefix', 'petscPCSetFromOptions', ...
    'petscPCSetUp', 'petscPCApply', 'petscPCApplyTranspose', ...
    'petscPCGetType', 'petscPCGetOptionsPrefix', ...
    'petscPCDestroy', ...
    ... % MPI
    'petscObjectGetComm', 'petscSplitOwnership', ...
    ... % Helpers
    'petscGetEnum', 'petscGetObject', ...
    };


% TODO:
% MatGetDiagonal, MatAXPY, MatMult, MatMultAdd,
% MatMultTranspose, MatMultTransposeAdd, MatNorm, MatDiagonalScale,
% MatScale, MatTranspose, MatZeroEntries, MatShift, MatZeroEntries
%
% VecAXPY, VecAYPX, VecWAXPY, VecAXPBY, VecScale,
% VecDot, VecTDot,  VecDotBegin, VecDotEnd, VecNorm, VecNormBegin,
% VecNormEnd, VecSum, VecCopy, VecSwap, VecPointwiseMult,
% VecPointwiseDivide, VecMDot, VecMTDOt, VeccMAXPTY, VecMax, VecMin,
% VecAbs, VecReciprocal, VecShift, VecSet.
%
% MatNullSpace, MatNullSpaceCreate,
%
% MatCholeskyFactor, MatLUFactor, MatGetFactor, MatReorderForNonzeroDiagonal
%
% , petscMatCreateAIJ, petscVecCreateMPI,
% MatGetType, MatCreateMPIAIJWithArrays, MatCreateSeqAIJWithArrays
% MatMPIAIJSetPreallocation, MatSeqAIJSetPreallocation
% MatSetNullSpace() and MatSetTransposeNullSpace()
% PCGetOperators, KSPGetOperators

% Unsupported: KSPRegister, PCRegister

for i=1:length(files)
    m2c(opts{:}, files{i});
end
