function build(varargin)

opts = [{'-mex', '-O', '-petsc'} varargin{:}];
files = {'petscGetEnum', 'petscGetObject', 'petscOptionsInsertString', ...
    'petscInitialize', 'petscInitialized', 'petscFinalize', 'petscFinalized', ...
    'petscVecCreateSeq', 'petscVecSetOption', 'petscVecSetOptionsPrefix', ...
    'petscVecSetFromOptions', 'petscVecSetValues', 'petscVecSet', ...
    'petscVecAssemblyBegin', 'petscVecAssemblyEnd', 'petscVecDestroy', ...
    'petscMatCreateSeqAIJ', 'petscMatSetOption', 'petscMatSetOptionsPrefix', ...
    'petscMatSetFromOptions', 'petscMatSetSizes', 'petscMatSetValues', ...
    'petscMatAssemblyBegin', 'petscMatAssemblyEnd', 'petscMatAssembled', ...
    'petscVecGetValues', 'petscMatDestroy'};

%petscAssembleMat
%petscAssembleVec

for i=1:length(files)
    m2c(opts{:}, files{i});
end
