/*
 * mpi/codegen/lib/mpi_Barrier/mpi_Barrier_mex.c
 *
 * Auxiliary code for mexFunction of mpi_Barrier
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {MPI_Comm}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "mpi_Barrier.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void mpi_Barrier_api(const mxArray ** prhs, const mxArray **plhs) {

    struct0_T            comm;
    mxArray              *_sub_mx1;

    int32_T              *info;
    boolean_T            *toplevel;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("mpi_Barrier:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("mpi_Barrier:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("mpi_Barrier:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mpi_Barrier:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("mpi_Barrier:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mpi_Barrier:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mpi_Barrier:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("mpi_Barrier:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mpi_Barrier:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("mpi_Barrier:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&info = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[1], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    mpi_Barrier_initialize();

    mpi_Barrier(&comm, info, toplevel);

    mpi_Barrier_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)comm.type); mxFree(comm.type);
    free_emxArray((emxArray__common*)comm.data); mxFree(comm.data);

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 1) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("mpi_Barrier:TooManyOutputArguments","Too many output arguments for entry-point mpi_Barrier.");
        /* Call the API function. */
        mpi_Barrier_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("mpi_Barrier:WrongNumberOfInputs","Incorrect number of input variables for entry-point mpi_Barrier.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}