/*
 * sys/codegen/lib/petscInitialized/petscInitialized_mex.c
 *
 * Auxiliary code for mexFunction of petscInitialized
 *
 * C source code generated by m2c.
 * %#m2c options:a86f06273668c7ee1c254c6a92bd888a
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "petscInitialized.h"
#include "petscInitialized_types.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __petscInitialized_api(mxArray **plhs, const mxArray ** prhs) {
    int32_T             *initialized;
    int32_T             *errCode;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    initialized = (int32_T*)mxMalloc(sizeof(int32_T));

    errCode = (int32_T*)mxMalloc(sizeof(int32_T));

    toplevel = (boolean_T*)mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    petscInitialized(initialized, errCode, toplevel);

    /* Deallocate input and marshall out function outputs */
    plhs[0] = move_scalar_to_mxArray(initialized, mxINT32_CLASS);
    plhs[1] = move_scalar_to_mxArray(errCode, mxINT32_CLASS);
    plhs[2] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3] = {NULL, NULL, NULL};
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 0) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("petscInitialized:TooManyOutputArguments",
                "Too many output arguments for entry-point petscInitialized.\n");
        /* Call the API function. */
        __petscInitialized_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("petscInitialized:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point petscInitialized.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}
