/*
 * sys/codegen/lib/petscOptionsGetBool/petscOptionsGetBool_mex.c
 *
 * Auxiliary code for mexFunction of petscOptionsGetBool
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {PetscOptions, coder.typeof(char(0), [1,inf]), coder.typeof(char(0), [1,inf])}  enableInline=1 withPetsc=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "petscOptionsGetBool.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void petscOptionsGetBool_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_char_T      pre;
    emxArray_char_T      name;

    struct0_T            opts;
    mxArray              *_sub_mx1;

    int32_T              *value;
    int32_T              *found;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongInputType",
            "Input argument opts has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("petscOptionsGetBool:InputStructWrongFields",
            "Input argument opts has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongSizeOfInputArg",
            "Argument opts must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongInputStruct",
            "Input argument opts does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongInputType",
            "Input argument opts.data has incorrect data type. uint8 is expected.");
    *(void**)&opts.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)opts.data, "opts.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongInputStruct",
            "Input argument opts does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongInputType",
            "Input argument opts.type has incorrect data type. char is expected.");
    *(void**)&opts.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)opts.type, "opts.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongInputStruct",
            "Input argument opts does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongInputType",
            "Input argument opts.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongSizeOfInputArg",
            "Argument opts.nitems should be a scalar.");
    opts.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongInputType",
            "Input argument pre has incorrect data type. char is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&pre, "pre", 2);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongInputType",
            "Input argument name has incorrect data type. char is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&name, "name", 2);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&value = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&found = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[2], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[3], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscOptionsGetBool_initialize();

    petscOptionsGetBool(&opts, &pre, &name, value, found, errCode, toplevel);

    petscOptionsGetBool_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */
    /* Nothing to do for plhs[3] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)opts.type); mxFree(opts.type);
    free_emxArray((emxArray__common*)opts.data); mxFree(opts.data);

    free_emxArray((emxArray__common*)&pre);
    free_emxArray((emxArray__common*)&name);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[4];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 3) {
        if (nlhs > 4)
            mexErrMsgIdAndTxt("petscOptionsGetBool:TooManyOutputArguments","Too many output arguments for entry-point petscOptionsGetBool.");
        /* Call the API function. */
        petscOptionsGetBool_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("petscOptionsGetBool:WrongNumberOfInputs","Incorrect number of input variables for entry-point petscOptionsGetBool.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}