/*
 * Mat/codegen/lib/petscMatDuplicate/petscMatDuplicate_mex.c
 *
 * Auxiliary code for mexFunction of petscMatDuplicate
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {PetscMat, int32(0)}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "petscMatDuplicate.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void petscMatDuplicate_api(const mxArray ** prhs, const mxArray **plhs) {

    struct0_T            mat_in;
    struct0_T            mat_out;
    mxArray              *_sub_mx1;

    int32_T              op;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongInputType",
            "Input argument mat_in has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("petscMatDuplicate:InputStructWrongFields",
            "Input argument mat_in has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongSizeOfInputArg",
            "Argument mat_in must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongInputStruct",
            "Input argument mat_in does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongInputType",
            "Input argument mat_in.data has incorrect data type. uint8 is expected.");
    *(void**)&mat_in.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)mat_in.data, "mat_in.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongInputStruct",
            "Input argument mat_in does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongInputType",
            "Input argument mat_in.type has incorrect data type. char is expected.");
    *(void**)&mat_in.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)mat_in.type, "mat_in.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongInputStruct",
            "Input argument mat_in does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongInputType",
            "Input argument mat_in.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongSizeOfInputArg",
            "Argument mat_in.nitems should be a scalar.");
    mat_in.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongInputType",
            "Input argument op has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongSizeOfInputArg",
            "Argument op should be a scalar.");
    op = *(int32_T*)mxGetData(prhs[1]);

    /* Preallocate output variables */
    *(void **)&mat_out.data = mxCalloc(1, sizeof(emxArray__common));    init_emxArray((emxArray__common*)mat_out.data, 1);
    *(void **)&mat_out.type = mxCalloc(1, sizeof(emxArray__common));    init_emxArray((emxArray__common*)mat_out.type, 2);
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscMatDuplicate_initialize();

    petscMatDuplicate(&mat_in, op, &mat_out, errCode, toplevel);

    petscMatDuplicate_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "data", "type", "nitems",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 3, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, move_emxArray_to_mxArray((emxArray__common*)mat_out.data, mxUINT8_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, move_emxArray_to_mxArray((emxArray__common*)mat_out.type, mxCHAR_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_scalar_to_mxArray(&mat_out.nitems, mxINT32_CLASS));
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)mat_in.type); mxFree(mat_in.type);
    free_emxArray((emxArray__common*)mat_in.data); mxFree(mat_in.data);

    free_emxArray((emxArray__common*)mat_out.type); mxFree(mat_out.type);
    free_emxArray((emxArray__common*)mat_out.data); mxFree(mat_out.data);

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 2) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("petscMatDuplicate:TooManyOutputArguments","Too many output arguments for entry-point petscMatDuplicate.");
        /* Call the API function. */
        petscMatDuplicate_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("petscMatDuplicate:WrongNumberOfInputs","Incorrect number of input variables for entry-point petscMatDuplicate.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}