/*
 * /Users/jiao/projects/NumGeom/ParaCoder/MPETSc/sys/codegen/lib/petscFinalized/petscFinalized_mex.c
 *
 * Auxiliary code for mexFunction of petscFinalized
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {}  enableInline=1 withPetsc=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "petscFinalized.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void petscFinalized_api(const mxArray ** prhs, const mxArray **plhs) {

    int32_T              *finalized;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&finalized = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscFinalized_initialize();

    petscFinalized(finalized, errCode, toplevel);

    petscFinalized_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 0) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("petscFinalized:TooManyOutputArguments","Too many output arguments for entry-point petscFinalized.");
        /* Call the API function. */
        petscFinalized_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("petscFinalized:WrongNumberOfInputs","Incorrect number of input variables for entry-point petscFinalized.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}