/*
 * Mat/codegen/lib/petscMatAXPY/petscMatAXPY_mex.c
 *
 * Auxiliary code for mexFunction of petscMatAXPY
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {PetscMat, 0, PetscMat, int32(0)} petscMatAXPY_3args -args {PetscMat, 0, PetscMat} enableInline=1 presVars=None dynMem=Threshold
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C header file generated by codegen in lib mode */
#include "petscMatAXPY.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

static void __petscMatAXPY_api(mxArray **plhs, const mxArray ** prhs) {

    struct0_T            Y;
    struct0_T            X;
    mxArray              *_sub_mx1;

    real64_T             a;
    int32_T              mstr;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument Y has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("petscMatAXPY:InputStructWrongFields",
            "Input argument Y has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongSizeOfInputArg",
            "Argument Y must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputStruct",
            "Input argument Y does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument Y.data has incorrect data type. uint8 is expected.");
    *(void**)&Y.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)Y.data, "Y.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputStruct",
            "Input argument Y does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument Y.type has incorrect data type. char is expected.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetDimensions(_sub_mx1)[0] != 1)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongSizeOfInputArg",
            "Dimension 1 of Y.type should be equal to 1.");
    *(void**)&Y.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)Y.type, "Y.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputStruct",
            "Input argument Y does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument Y.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongSizeOfInputArg",
            "Argument Y.nitems should be a scalar.");
    Y.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument a has incorrect data type; double is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongSizeOfInputArg",
            "Argument a should be a scalar.");
    a = *(real64_T*)mxGetData(prhs[1]);

    if (!mxIsStruct(prhs[2]))
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument X has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[2])!=3)
        mexErrMsgIdAndTxt("petscMatAXPY:InputStructWrongFields",
            "Input argument X has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongSizeOfInputArg",
            "Argument X must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[2], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputStruct",
            "Input argument X does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument X.data has incorrect data type. uint8 is expected.");
    *(void**)&X.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)X.data, "X.data", 1);
    _sub_mx1 = mxGetField(prhs[2], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputStruct",
            "Input argument X does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument X.type has incorrect data type. char is expected.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetDimensions(_sub_mx1)[0] != 1)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongSizeOfInputArg",
            "Dimension 1 of X.type should be equal to 1.");
    *(void**)&X.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)X.type, "X.type", 2);
    _sub_mx1 = mxGetField(prhs[2], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputStruct",
            "Input argument X does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument X.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongSizeOfInputArg",
            "Argument X.nitems should be a scalar.");
    X.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongInputType",
            "Input argument mstr has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY:WrongSizeOfInputArg",
            "Argument mstr should be a scalar.");
    mstr = *(int32_T*)mxGetData(prhs[3]);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[1], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscMatAXPY(&Y, a, &X, mstr, errCode, toplevel);

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)Y.type); mxFree(Y.type);
    free_emxArray((emxArray__common*)Y.data); mxFree(Y.data);

    free_emxArray((emxArray__common*)X.type); mxFree(X.type);
    free_emxArray((emxArray__common*)X.data); mxFree(X.data);

}
static void __petscMatAXPY_3args_api(mxArray **plhs, const mxArray ** prhs) {

    struct0_T            Y;
    struct0_T            X;
    mxArray              *_sub_mx1;

    real64_T             a;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputType",
            "Input argument Y has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:InputStructWrongFields",
            "Input argument Y has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongSizeOfInputArg",
            "Argument Y must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputStruct",
            "Input argument Y does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputType",
            "Input argument Y.data has incorrect data type. uint8 is expected.");
    *(void**)&Y.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)Y.data, "Y.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputStruct",
            "Input argument Y does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputType",
            "Input argument Y.type has incorrect data type. char is expected.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetDimensions(_sub_mx1)[0] != 1)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongSizeOfInputArg",
            "Dimension 1 of Y.type should be equal to 1.");
    *(void**)&Y.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)Y.type, "Y.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputStruct",
            "Input argument Y does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputType",
            "Input argument Y.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongSizeOfInputArg",
            "Argument Y.nitems should be a scalar.");
    Y.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputType",
            "Input argument a has incorrect data type; double is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongSizeOfInputArg",
            "Argument a should be a scalar.");
    a = *(real64_T*)mxGetData(prhs[1]);

    if (!mxIsStruct(prhs[2]))
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputType",
            "Input argument X has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[2])!=3)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:InputStructWrongFields",
            "Input argument X has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongSizeOfInputArg",
            "Argument X must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[2], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputStruct",
            "Input argument X does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputType",
            "Input argument X.data has incorrect data type. uint8 is expected.");
    *(void**)&X.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)X.data, "X.data", 1);
    _sub_mx1 = mxGetField(prhs[2], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputStruct",
            "Input argument X does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputType",
            "Input argument X.type has incorrect data type. char is expected.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetDimensions(_sub_mx1)[0] != 1)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongSizeOfInputArg",
            "Dimension 1 of X.type should be equal to 1.");
    *(void**)&X.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)X.type, "X.type", 2);
    _sub_mx1 = mxGetField(prhs[2], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputStruct",
            "Input argument X does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongInputType",
            "Input argument X.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscMatAXPY_3args:WrongSizeOfInputArg",
            "Argument X.nitems should be a scalar.");
    X.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[1], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscMatAXPY_3args(&Y, a, &X, errCode, toplevel);

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)Y.type); mxFree(Y.type);
    free_emxArray((emxArray__common*)Y.data); mxFree(Y.data);

    free_emxArray((emxArray__common*)X.type); mxFree(X.type);
    free_emxArray((emxArray__common*)X.data); mxFree(X.data);

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 4) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("petscMatAXPY:TooManyOutputArguments",
                "Too many output arguments for entry-point petscMatAXPY.\n");
        /* Call the API function. */
        __petscMatAXPY_api(outputs, prhs);
    }
    else if (nrhs == 3) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("petscMatAXPY_3args:TooManyOutputArguments",
                "Too many output arguments for entry-point petscMatAXPY_3args.\n");
        /* Call the API function. */
        __petscMatAXPY_3args_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("petscMatAXPY:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point petscMatAXPY.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}