/*
 * sys/codegen/lib/mpi_Finalized/mpi_Finalized_mex.c
 *
 * Auxiliary code for mexFunction of mpi_Finalized
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {}  enableInline=1 withPetsc=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "mpi_Finalized.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void mpi_Finalized_api(const mxArray ** prhs, const mxArray **plhs) {

    int32_T              *flag;
    int32_T              *info;
    boolean_T            *toplevel;

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&flag = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&info = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    mpi_Finalized_initialize();

    mpi_Finalized(flag, info, toplevel);

    mpi_Finalized_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 0) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("mpi_Finalized:TooManyOutputArguments","Too many output arguments for entry-point mpi_Finalized.");
        /* Call the API function. */
        mpi_Finalized_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("mpi_Finalized:WrongNumberOfInputs","Incorrect number of input variables for entry-point mpi_Finalized.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}