/*
 * petsc/codegen/lib/petscVecGetValues/petscVecGetValues_mex.c
 *
 * Auxiliary code for mexFunction of petscVecGetValues
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {PetscVec, int32(0), coder.typeof(int32(0), [inf,1]), coder.typeof(0, [inf,1])} petscVecGetValues_Alloc -args {PetscVec, int32(0), coder.typeof(int32(0), [inf,1])}  enableInline=1 withPetsc=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "petscVecGetValues.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void petscVecGetValues_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     ix;
    emxArray_real_T      y;

    struct0_T            vec;
    mxArray              *_sub_mx1;

    int32_T              ni;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputType",
            "Input argument vec has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("petscVecGetValues:InputStructWrongFields",
            "Input argument vec has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongSizeOfInputArg",
            "Argument vec must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputStruct",
            "Input argument vec does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputType",
            "Input argument vec.data has incorrect data type. uint8 is expected.");
    *(void**)&vec.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)vec.data, "vec.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputStruct",
            "Input argument vec does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputType",
            "Input argument vec.type has incorrect data type. char is expected.");
    *(void**)&vec.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)vec.type, "vec.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputStruct",
            "Input argument vec does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputType",
            "Input argument vec.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongSizeOfInputArg",
            "Argument vec.nitems should be a scalar.");
    vec.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputType",
            "Input argument ni has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongSizeOfInputArg",
            "Argument ni should be a scalar.");
    ni = *(int32_T*)mxGetData(prhs[1]);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputType",
            "Input argument ix has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&ix, "ix", 1);
    plhs[0] = mxDuplicateArray(prhs[3]);
    if (mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues:WrongInputType",
            "Input argument y has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&y, "y", 1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscVecGetValues_initialize();

    petscVecGetValues(&vec, ni, &ix, &y, errCode, toplevel);

    petscVecGetValues_terminate();

    /* Marshall out function outputs */
    if (y.canFreeData) plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&y, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)vec.type); mxFree(vec.type);
    free_emxArray((emxArray__common*)vec.data); mxFree(vec.data);

    free_emxArray((emxArray__common*)&ix);
    free_emxArray((emxArray__common*)&y);
}
void petscVecGetValues_Alloc_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     ix;
    emxArray_real_T      y;

    struct0_T            vec;
    mxArray              *_sub_mx1;

    int32_T              ni;
    int32_T              *errCode;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongInputType",
            "Input argument vec has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:InputStructWrongFields",
            "Input argument vec has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongSizeOfInputArg",
            "Argument vec must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongInputStruct",
            "Input argument vec does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongInputType",
            "Input argument vec.data has incorrect data type. uint8 is expected.");
    *(void**)&vec.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)vec.data, "vec.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongInputStruct",
            "Input argument vec does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongInputType",
            "Input argument vec.type has incorrect data type. char is expected.");
    *(void**)&vec.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)vec.type, "vec.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongInputStruct",
            "Input argument vec does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongInputType",
            "Input argument vec.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongSizeOfInputArg",
            "Argument vec.nitems should be a scalar.");
    vec.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongInputType",
            "Input argument ni has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongSizeOfInputArg",
            "Argument ni should be a scalar.");
    ni = *(int32_T*)mxGetData(prhs[1]);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscVecGetValues_Alloc:WrongInputType",
            "Input argument ix has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&ix, "ix", 1);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&y, 1);
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscVecGetValues_initialize();

    petscVecGetValues_Alloc(&vec, ni, &ix, &y, errCode);

    petscVecGetValues_terminate();

    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&y, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[1] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)vec.type); mxFree(vec.type);
    free_emxArray((emxArray__common*)vec.data); mxFree(vec.data);

    free_emxArray((emxArray__common*)&ix);
    free_emxArray((emxArray__common*)&y);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 4) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("petscVecGetValues:TooManyOutputArguments","Too many output arguments for entry-point petscVecGetValues.");
        /* Call the API function. */
        petscVecGetValues_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 3) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("petscVecGetValues_Alloc:TooManyOutputArguments","Too many output arguments for entry-point petscVecGetValues_Alloc.");
        /* Call the API function. */
        petscVecGetValues_Alloc_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("petscVecGetValues:WrongNumberOfInputs","Incorrect number of input variables for entry-point petscVecGetValues.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}