/*
 * sys/codegen/lib/petscGetString/petscGetString_mex.c
 *
 * Auxiliary code for mexFunction of petscGetString
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {coder.typeof(char(0),[1,inf])}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "petscGetString.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void petscGetString_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_char_T      name;
    emxArray_char_T      str;

    boolean_T            *toplevel;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscGetString:WrongInputType",
            "Input argument name has incorrect data type. char is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&name, "name", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&str, 2);
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[1], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscGetString_initialize();

    petscGetString(&name, &str, toplevel);

    petscGetString_terminate();

    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&str, mxCHAR_CLASS);
    /* Nothing to do for plhs[1] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&name);
    free_emxArray((emxArray__common*)&str);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 1) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("petscGetString:TooManyOutputArguments","Too many output arguments for entry-point petscGetString.");
        /* Call the API function. */
        petscGetString_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("petscGetString:WrongNumberOfInputs","Incorrect number of input variables for entry-point petscGetString.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}