/*
 * sys/codegen/lib/petscObjectGetComm/petscObjectGetComm_mex.c
 *
 * Auxiliary code for mexFunction of petscObjectGetComm
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {PetscObject}  enableInline=1 withPetsc=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "petscObjectGetComm.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void petscObjectGetComm_api(const mxArray ** prhs, const mxArray **plhs) {

    struct0_T            obj;
    struct0_T            comm;
    mxArray              *_sub_mx1;

    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongInputType",
            "Input argument obj has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("petscObjectGetComm:InputStructWrongFields",
            "Input argument obj has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongSizeOfInputArg",
            "Argument obj must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongInputStruct",
            "Input argument obj does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongInputType",
            "Input argument obj.data has incorrect data type. uint8 is expected.");
    *(void**)&obj.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)obj.data, "obj.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongInputStruct",
            "Input argument obj does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongInputType",
            "Input argument obj.type has incorrect data type. char is expected.");
    *(void**)&obj.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)obj.type, "obj.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongInputStruct",
            "Input argument obj does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongInputType",
            "Input argument obj.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongSizeOfInputArg",
            "Argument obj.nitems should be a scalar.");
    obj.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    *(void **)&comm.data = mxCalloc(1, sizeof(emxArray__common));    init_emxArray((emxArray__common*)comm.data, 1);
    *(void **)&comm.type = mxCalloc(1, sizeof(emxArray__common));    init_emxArray((emxArray__common*)comm.type, 2);
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscObjectGetComm_initialize();

    petscObjectGetComm(&obj, &comm, errCode, toplevel);

    petscObjectGetComm_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "data", "type", "nitems",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 3, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, move_emxArray_to_mxArray((emxArray__common*)comm.data, mxUINT8_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, move_emxArray_to_mxArray((emxArray__common*)comm.type, mxCHAR_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_scalar_to_mxArray(&comm.nitems, mxINT32_CLASS));
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)obj.type); mxFree(obj.type);
    free_emxArray((emxArray__common*)obj.data); mxFree(obj.data);

    free_emxArray((emxArray__common*)comm.type); mxFree(comm.type);
    free_emxArray((emxArray__common*)comm.data); mxFree(comm.data);

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 1) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("petscObjectGetComm:TooManyOutputArguments","Too many output arguments for entry-point petscObjectGetComm.");
        /* Call the API function. */
        petscObjectGetComm_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("petscObjectGetComm:WrongNumberOfInputs","Incorrect number of input variables for entry-point petscObjectGetComm.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}