/*
 * Mat/codegen/lib/petscMatGetInfo/petscMatGetInfo_mex.c
 *
 * Auxiliary code for mexFunction of petscMatGetInfo
 *
 * C source code generated by m2c.
 * %#m2c options:cb90f48061e18ca07fb0b645e3651c33
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "petscMatGetInfo.h"
#include "petscMatGetInfo_types.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void marshallin_const_M2C_OpaqueType(M2C_OpaqueType *pStruct, const mxArray *mx, const char *mname) {
    mxArray             *sub_mx;

    if (!mxIsStruct(mx))
        M2C_error("marshallin_const_M2C_OpaqueType:WrongType",
            "Input argument %s has incorrect data type; struct is expected.", mname);
    if (!mxGetField(mx, 0, "data"))
        M2C_error("marshallin_const_M2C_OpaqueType:WrongType",
            "Input argument %s is missing the field data.", mname);
    if (!mxGetField(mx, 0, "type"))
        M2C_error("marshallin_const_M2C_OpaqueType:WrongType",
            "Input argument %s is missing the field type.", mname);
    if (!mxGetField(mx, 0, "nitems"))
        M2C_error("marshallin_const_M2C_OpaqueType:WrongType",
            "Input argument %s is missing the field nitems.", mname);
    if (mxGetNumberOfFields(mx) > 3)
        M2C_warn("marshallin_const_M2C_OpaqueType:ExtraFields",
            "Extra fields in %s and are ignored.", mname);

    sub_mx = mxGetField(mx, 0, "data");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("marshallin_const_M2C_OpaqueType:WrongInputType",
            "Input argument data has incorrect data type; uint8 is expected.");
    if (mxGetNumberOfElements(sub_mx) && mxGetDimensions(sub_mx)[1] != 1) 
        mexErrMsgIdAndTxt("marshallin_const_M2C_OpaqueType:WrongSizeOfInputArg",
            "Dimension 2 of data should be equal to 1.");
    pStruct->data = (emxArray_uint8_T*)mxMalloc(sizeof(emxArray_uint8_T));
    init_emxArray((emxArray__common*)(pStruct->data), 1);
    alias_mxArray_to_emxArray(sub_mx, (emxArray__common *)(pStruct->data), "data", 1);

    sub_mx = mxGetField(mx, 0, "type");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("marshallin_const_M2C_OpaqueType:WrongInputType",
            "Input argument type has incorrect data type; char is expected.");
    if (mxGetNumberOfElements(sub_mx) && mxGetDimensions(sub_mx)[0] != 1) 
        mexErrMsgIdAndTxt("marshallin_const_M2C_OpaqueType:WrongSizeOfInputArg",
            "Dimension 1 of type should be equal to 1.");
    pStruct->type = (emxArray_char_T*)mxMalloc(sizeof(emxArray_char_T));
    init_emxArray((emxArray__common*)(pStruct->type), 2);
    alias_mxArray_to_emxArray(sub_mx, (emxArray__common *)(pStruct->type), "type", 2);

    sub_mx = mxGetField(mx, 0, "nitems");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("marshallin_const_M2C_OpaqueType:WrongInputType",
            "Input argument nitems has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(sub_mx) != 1)
        mexErrMsgIdAndTxt("marshallin_const_M2C_OpaqueType:WrongSizeOfInputArg",
            "Argument nitems should be a scalar.");
    pStruct->nitems = *(int32_T*)mxGetData(sub_mx);
}
static void destroy_M2C_OpaqueType(M2C_OpaqueType *pStruct) {

    free_emxArray((emxArray__common*)(pStruct->data));
    mxFree(pStruct->data);

    free_emxArray((emxArray__common*)(pStruct->type));
    mxFree(pStruct->type);


}


static mxArray *marshallout_PetscMatInfo(PetscMatInfo *pStruct) {
    const char           *fields[] = {"block_size", "nz_allocated", "nz_used", "nz_unneeded", "memory", "assemblies", "mallocs", "fill_ratio_given", "fill_ratio_needed", "factor_mallocs"};
    int                  one=1;
    mxArray              *mx = create_struct_mxArray(1, &one, 10, fields);

    mxSetField(mx, 0, "block_size", copy_scalar_to_mxArray(&pStruct->block_size, mxDOUBLE_CLASS));
    mxSetField(mx, 0, "nz_allocated", copy_scalar_to_mxArray(&pStruct->nz_allocated, mxDOUBLE_CLASS));
    mxSetField(mx, 0, "nz_used", copy_scalar_to_mxArray(&pStruct->nz_used, mxDOUBLE_CLASS));
    mxSetField(mx, 0, "nz_unneeded", copy_scalar_to_mxArray(&pStruct->nz_unneeded, mxDOUBLE_CLASS));
    mxSetField(mx, 0, "memory", copy_scalar_to_mxArray(&pStruct->memory, mxDOUBLE_CLASS));
    mxSetField(mx, 0, "assemblies", copy_scalar_to_mxArray(&pStruct->assemblies, mxDOUBLE_CLASS));
    mxSetField(mx, 0, "mallocs", copy_scalar_to_mxArray(&pStruct->mallocs, mxDOUBLE_CLASS));
    mxSetField(mx, 0, "fill_ratio_given", copy_scalar_to_mxArray(&pStruct->fill_ratio_given, mxDOUBLE_CLASS));
    mxSetField(mx, 0, "fill_ratio_needed", copy_scalar_to_mxArray(&pStruct->fill_ratio_needed, mxDOUBLE_CLASS));
    mxSetField(mx, 0, "factor_mallocs", copy_scalar_to_mxArray(&pStruct->factor_mallocs, mxDOUBLE_CLASS));
    return mx;
}



static void __petscMatGetInfo_api(mxArray **plhs, const mxArray ** prhs) {
    M2C_OpaqueType       mat;
    int32_T              flag;
    PetscMatInfo         info;
    int32_T             *errCode;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxSTRUCT_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputType",
            "Input argument mat has incorrect data type; struct is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongSizeOfInputArg",
            "Argument mat should be a scalar.");
    marshallin_const_M2C_OpaqueType(&mat, prhs[0], "mat");

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputType",
            "Input argument flag has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongSizeOfInputArg",
            "Argument flag should be a scalar.");
    flag = *(int32_T*)mxGetData(prhs[1]);

    errCode = (int32_T*)mxMalloc(sizeof(int32_T));

    toplevel = (boolean_T*)mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    petscMatGetInfo(&mat, flag, &info, errCode, toplevel);

    /* Deallocate input and marshall out function outputs */
    destroy_M2C_OpaqueType(&mat);
    /* Nothing to be done for flag */
    plhs[0] = marshallout_PetscMatInfo(&info);
    plhs[1] = move_scalar_to_mxArray(errCode, mxINT32_CLASS);
    plhs[2] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}

static void __petscMatGetInfo_Local_api(mxArray **plhs, const mxArray ** prhs) {
    M2C_OpaqueType       mat;
    PetscMatInfo         info;
    int32_T             *errCode;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxSTRUCT_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongInputType",
            "Input argument mat has incorrect data type; struct is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongSizeOfInputArg",
            "Argument mat should be a scalar.");
    marshallin_const_M2C_OpaqueType(&mat, prhs[0], "mat");

    errCode = (int32_T*)mxMalloc(sizeof(int32_T));

    toplevel = (boolean_T*)mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    petscMatGetInfo_Local(&mat, &info, errCode, toplevel);

    /* Deallocate input and marshall out function outputs */
    destroy_M2C_OpaqueType(&mat);
    plhs[0] = marshallout_PetscMatInfo(&info);
    plhs[1] = move_scalar_to_mxArray(errCode, mxINT32_CLASS);
    plhs[2] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3] = {NULL, NULL, NULL};
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 2) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("petscMatGetInfo:TooManyOutputArguments",
                "Too many output arguments for entry-point petscMatGetInfo.\n");
        /* Call the API function. */
        __petscMatGetInfo_api(outputs, prhs);
    }
    else if (nrhs == 1) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("petscMatGetInfo_Local:TooManyOutputArguments",
                "Too many output arguments for entry-point petscMatGetInfo_Local.\n");
        /* Call the API function. */
        __petscMatGetInfo_Local_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point petscMatGetInfo.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}
