/*
 * Mat/codegen/lib/petscMatGetInfo/petscMatGetInfo_mex.c
 *
 * Auxiliary code for mexFunction of petscMatGetInfo
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {PetscMat, int32(0)} petscMatGetInfo_Local -args {PetscMat}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "petscMatGetInfo.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void petscMatGetInfo_api(const mxArray ** prhs, const mxArray **plhs) {

    struct0_T            mat;
    MPetscMatInfo        info;
    mxArray              *_sub_mx1;

    int32_T              flag;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputType",
            "Input argument mat has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("petscMatGetInfo:InputStructWrongFields",
            "Input argument mat has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongSizeOfInputArg",
            "Argument mat must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputStruct",
            "Input argument mat does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputType",
            "Input argument mat.data has incorrect data type. uint8 is expected.");
    *(void**)&mat.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)mat.data, "mat.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputStruct",
            "Input argument mat does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputType",
            "Input argument mat.type has incorrect data type. char is expected.");
    *(void**)&mat.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)mat.type, "mat.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputStruct",
            "Input argument mat does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputType",
            "Input argument mat.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongSizeOfInputArg",
            "Argument mat.nitems should be a scalar.");
    mat.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongInputType",
            "Input argument flag has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongSizeOfInputArg",
            "Argument flag should be a scalar.");
    flag = *(int32_T*)mxGetData(prhs[1]);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscMatGetInfo_initialize();

    petscMatGetInfo(&mat, flag, &info, errCode, toplevel);

    petscMatGetInfo_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "block_size", "nz_allocated", "nz_used", "nz_unneeded", "memory", "assemblies", "mallocs", "fill_ratio_given", "fill_ratio_needed", "factor_mallocs",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 10, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, copy_scalar_to_mxArray(&info.block_size, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, copy_scalar_to_mxArray(&info.nz_allocated, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_scalar_to_mxArray(&info.nz_used, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 3, copy_scalar_to_mxArray(&info.nz_unneeded, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 4, copy_scalar_to_mxArray(&info.memory, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 5, copy_scalar_to_mxArray(&info.assemblies, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 6, copy_scalar_to_mxArray(&info.mallocs, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 7, copy_scalar_to_mxArray(&info.fill_ratio_given, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 8, copy_scalar_to_mxArray(&info.fill_ratio_needed, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 9, copy_scalar_to_mxArray(&info.factor_mallocs, mxDOUBLE_CLASS));
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)mat.type); mxFree(mat.type);
    free_emxArray((emxArray__common*)mat.data); mxFree(mat.data);

}
void petscMatGetInfo_Local_api(const mxArray ** prhs, const mxArray **plhs) {

    struct0_T            mat;
    MPetscMatInfo        info;
    mxArray              *_sub_mx1;

    int32_T              *errCode;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongInputType",
            "Input argument mat has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:InputStructWrongFields",
            "Input argument mat has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongSizeOfInputArg",
            "Argument mat must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongInputStruct",
            "Input argument mat does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongInputType",
            "Input argument mat.data has incorrect data type. uint8 is expected.");
    *(void**)&mat.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)mat.data, "mat.data", 1);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongInputStruct",
            "Input argument mat does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongInputType",
            "Input argument mat.type has incorrect data type. char is expected.");
    *(void**)&mat.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)mat.type, "mat.type", 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongInputStruct",
            "Input argument mat does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongInputType",
            "Input argument mat.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("petscMatGetInfo_Local:WrongSizeOfInputArg",
            "Argument mat.nitems should be a scalar.");
    mat.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }

    /* Invoke the target function */
    petscMatGetInfo_initialize();

    petscMatGetInfo_Local(&mat, &info, errCode);

    petscMatGetInfo_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "block_size", "nz_allocated", "nz_used", "nz_unneeded", "memory", "assemblies", "mallocs", "fill_ratio_given", "fill_ratio_needed", "factor_mallocs",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 10, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, copy_scalar_to_mxArray(&info.block_size, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, copy_scalar_to_mxArray(&info.nz_allocated, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_scalar_to_mxArray(&info.nz_used, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 3, copy_scalar_to_mxArray(&info.nz_unneeded, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 4, copy_scalar_to_mxArray(&info.memory, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 5, copy_scalar_to_mxArray(&info.assemblies, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 6, copy_scalar_to_mxArray(&info.mallocs, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 7, copy_scalar_to_mxArray(&info.fill_ratio_given, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 8, copy_scalar_to_mxArray(&info.fill_ratio_needed, mxDOUBLE_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 9, copy_scalar_to_mxArray(&info.factor_mallocs, mxDOUBLE_CLASS));
    /* Nothing to do for plhs[1] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)mat.type); mxFree(mat.type);
    free_emxArray((emxArray__common*)mat.data); mxFree(mat.data);

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 2) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("petscMatGetInfo:TooManyOutputArguments","Too many output arguments for entry-point petscMatGetInfo.");
        /* Call the API function. */
        petscMatGetInfo_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 1) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("petscMatGetInfo_Local:TooManyOutputArguments","Too many output arguments for entry-point petscMatGetInfo_Local.");
        /* Call the API function. */
        petscMatGetInfo_Local_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("petscMatGetInfo:WrongNumberOfInputs","Incorrect number of input variables for entry-point petscMatGetInfo.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}